# Lesson 6 - Numpy

**NumPy** (*Numerical Python*) is the cornerstone of numerical computing in Python. Here's why it's essential:

## 🚀 Key Features
- **N-Dimensional Arrays**:  
  Efficient `ndarray` object for storing homogeneous data (integers, floats, etc.)  
  ```python
  import numpy as np
  arr = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array
  ```
- **Vectorization**:  
  Perform operations on entire arrays *without loops*
  ```python
  a = np.array([1, 2, 3])
  b = np.array([4, 5, 6])
  print(a * b)  # [4, 10, 18]
  ```
- **Speed**:  
  Built-in C/C++/Fortran optimizations make it **100x faster** than Python lists for large datasets
- **Scientific Toolkit**:
  - Linear algebra(```np.linalg```)
  - Fourier transforms(```np.fft```)
  - Random sampling(```np.random```)
  - Statistics and matrix operations


## 🚀 Key Features
- **N-Dimensional Arrays**:  
  Efficient `ndarray` object for storing homogeneous data (integers, floats, etc.)  
  ```python
  import numpy as np
  arr = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array

In [1]:
import numpy as np

a = np.array([[1], [2]])
print(a)
print(a.shape)
print(a.ndim)

M = np.array([[[7, 7], [8, 8], [9, 9]], [[10, 10], [11, 11], [12, 12]]])
print(M)
print("shape: ", M.shape)
print("ndim: ", M.ndim)
print("size: ", M.size)
print("dtype: ", M.dtype)


A = np.array([[1, 2], [3, 4]])

x = np.array([[1], [0]])

[[1]
 [2]]
(2, 1)
2
[[[ 7  7]
  [ 8  8]
  [ 9  9]]

 [[10 10]
  [11 11]
  [12 12]]]
shape:  (2, 3, 2)
ndim:  3
size:  12
dtype:  int64


In [2]:
zeros = np.zeros((2, 2))
print(zeros)

ones = 2 * np.ones((2, 2))  # Create an array of all ones
print(ones)

eye = np.eye(3)  # Create a 2x2 identity matrix
print(eye)

[[0. 0.]
 [0. 0.]]
[[2. 2.]
 [2. 2.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
import math


range_array = np.arange(0, 10, 2)  # Create an array of range with step 2
print(range_array)

linespace_array = np.linspace(0, 3.23, 3)  # Create an array of 6 elements between 0 and 10
print(linespace_array)
print(linespace_array.dtype)


[0 2 4 6 8]
[0.    1.615 3.23 ]
float64


In [4]:
x = np.sqrt(4)
print(x**2)

4.0


In [5]:
x = range(10, 1, -2)
print(list(x))

[10, 8, 6, 4, 2]


In [6]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(f"np.dot(x, y) = {np.dot(x, y)}")
print(f"x @ y = {x @ y}")
print(f"x * y = {x * y}")
print(f"5 * y = {5 * y}")

print(f"np.cross(x, y) = {np.cross(x, y)}")



np.dot(x, y) = 32
x @ y = 32
x * y = [ 4 10 18]
5 * y = [20 25 30]
np.cross(x, y) = [-3  6 -3]


In [7]:
a = np.array([[[[1]], [[2]], [[3]]]])
b = np.array([1, 2, 3])
print(f"a = {a}")
a = a.flatten()
print(f"a = {a}")
print(b)
print(a + b)


print(np.append(a, b))

print(np.insert(a, 1, 7))

A = np.array([[1.0, 2.0], [3.0, 4.0]])
print(f"A = {A}")

# A = np.insert(A, 1, [7, 8], axis=1)
print(f"A = \n{A}")

# print(f"A.T = \n{A.T}")
# print(f"np.invert(A) = \n{np.invert(A)}")
# print(f"np.invert(A) * A = \n{np.invert(A) * A}")
print(f"np.linalg.inv(A) = \n{np.linalg.inv(A)}")
print(f"np.linalg.inv(A) * A = \n{np.linalg.inv(A) * A}")

a = [[[[1]]

  [[2]]

  [[3]]]]
a = [1 2 3]
[1 2 3]
[2 4 6]
[1 2 3 1 2 3]
[1 7 2 3]
A = [[1. 2.]
 [3. 4.]]
A = 
[[1. 2.]
 [3. 4.]]
np.linalg.inv(A) = 
[[-2.   1. ]
 [ 1.5 -0.5]]
np.linalg.inv(A) * A = 
[[-2.   2. ]
 [ 4.5 -2. ]]


In [8]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(f"a = {a}")
print(f"b = {b}")

v_stack = np.vstack((a, b))  # Vertical
h_stack = np.hstack((a, b))  # Horizontal

print(f"v_stack = {v_stack}")
print(f"h_stack = {h_stack}")

print(f"v_stack[0:1, -1] = {v_stack[0:1, -1]}")

a = [[1 2]
 [3 4]]
b = [[5 6]
 [7 8]]
v_stack = [[1 2]
 [3 4]
 [5 6]
 [7 8]]
h_stack = [[1 2 5 6]
 [3 4 7 8]]
v_stack[0:1, -1] = [2]


In [9]:
a = np.array([[1, 2], [3, 4]])
print(f"a = \n{a}")

b = a > 2
print(f"a > 2 = \n{b}")

b = a[b]
print(f"b = \n{b}")

a = 
[[1 2]
 [3 4]]
a > 2 = 
[[False False]
 [ True  True]]
b = 
[3 4]


In [10]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(f"a = \n{a}")
rows = list(range(a.shape[0]))
cols = list(range(a.shape[0]))
print("\nSelected elements:", a[rows, cols])

a = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Selected elements: [ 1  6 11 16]
