# Lesson 6 - NumPy

In this lesson we will get to know the **NumPy** (*Numerical Python*) library and understand why it's essential for numerical computing in python.


## 🚀 Key Features
- **N-Dimensional Arrays**:  
  Efficient `ndarray` object for storing homogeneous data (integers, floats, etc.)  
  ```python
  import numpy as np
  arr = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array
  ```
- **Vectorization**:  
  Perform operations on entire arrays *without loops*
  ```python
  a = np.array([1, 2, 3])
  b = np.array([4, 5, 6])
  print(a * b)  # [4, 10, 18]
  ```
- **Speed**:  
  Built-in C/C++/Fortran optimizations make it **100x faster** than Python lists for large datasets

- **Scientific Toolkit**:
  - Linear algebra (```np.linalg```)
  - Fourier transforms (```np.fft```)
  - Random sampling (```np.random```)
  - Statistics and matrix operations

## 🌐 Ecosystem Integration
Serves as the foundation for:
- [Pandas](https://pandas.pydata.org/) (DataFrames)
- [SciPy](https://scipy.org/) (Scientific computing)
- [Matplotlib](https://matplotlib.org/)/[Seaborn](https://seaborn.pydata.org/) (Visualization)
- [scikit-learn](https://scikit-learn.org/stable/) (Machine Learning)

## 💡 Why Learn NumPy?

- **Data Science**: Cleaning/transforming datasets
- **Machine Learning**: Matrix operations for neural nets
- **Physics Simulations**: Modeling wave propagation
- **Financial Analysis**: Portfolio optimization
- **Image Processing**: Manipulating pixel arrays

## 0 Installation and Import

In order to use NUmPy, you have to first install the NumPy library using pip (inside the python environment) and than import it inside your code.

```bash
> pip install numpy
```

```python
import numpy as np
```

## 1 Beginner Level

### 1.1 Creating Arrays

Here are some examples for creating NumPy-Arrays.

In [1]:
import numpy as np


# 1D Array
arr1d = np.array([1, 2, 3, 4, 5]) 
print("1D Array:", arr1d)

# 2D Array (Matrix)
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr2d)

# Special Arrays
zeros = np.zeros((2, 3)) # 2x3 matrix of zeros
ones = np.ones((3, 2)) # 3x2 matrix of ones
eye = np.eye(3)  # Identity matrix
range_arr = np.arange(0, 10, 2)  # Like range() but returns array
linspace_arr = np.linspace(0, 1, 5)  # 5 evenly spaced numbers

print("\nZeros:\n", zeros)
print("\nOnes:\n", ones)
print("\nIdentity Matrix:\n", eye)
print("\nRange Array:", range_arr)
print("\nLinspace Array:", linspace_arr)

1D Array: [1 2 3 4 5]

2D Array:
 [[1 2 3]
 [4 5 6]]

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Range Array: [0 2 4 6 8]

Linspace Array: [0.   0.25 0.5  0.75 1.  ]


### 1.2 Array Attributes

NumPy arrays have attributes which can be accessed. Some of them are shown in the next code block.

In [2]:
print("\nShape:", arr2d.shape)
print("Dimensions:", arr2d.ndim)
print("Size:", arr2d.size)
print("Data Type:", arr2d.dtype)


Shape: (2, 3)
Dimensions: 2
Size: 6
Data Type: int64


### 1.3 Basic Operations

All the basic vector and matrix operations are supported for NumPy arrays.

In [3]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(f"x = {x}")
print(f"y = {y}")

print("\nSome Vector Operations:")

print(f"np.dot(x, y) = {np.dot(x, y)}") # Dot product
print(f"x @ y = {x @ y}") # Dot product
print(f"x * y = {x * y}") # Element-wise multiplication
print(f"5 * y = {5 * y}") # Scalar multiplication
print(f"np.cross(x, y) = {np.cross(x, y)}") # Cross product

x = [1 2 3]
y = [4 5 6]

Some Vector Operations:
np.dot(x, y) = 32
x @ y = 32
x * y = [ 4 10 18]
5 * y = [20 25 30]
np.cross(x, y) = [-3  6 -3]


### 1.4 Aggregation Functions

All the common aggregation functions are also supported.

In [4]:
matrix = np.random.randint(0, 10, (3, 3))
print(f"\nMatrix:\n{matrix}\n")
print("Sum:", matrix.sum())
print("Column maxima:", matrix.max(axis=0))
print("Row means:", matrix.mean(axis=1))


Matrix:
[[2 6 9]
 [8 9 2]
 [7 9 7]]

Sum: 59
Column maxima: [8 9 9]
Row means: [5.66666667 6.33333333 7.66666667]


## 2 Intermediate Level

### 2.1 Reshaping Arrays

In [5]:
array = np.arange(1, 13) # 1D Array
reshaped = array.reshape(3, 4)  # Reshape to 3x4 matrix (total elements must match)
flattened = reshaped.flatten() # Flatten back to 1D array

print("\nOriginal:\n", array)
print("\nReshaped:\n", reshaped)
print("\nFlattened:\n", flattened)


Original:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Flattened:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


### 2.2  Adding/Removing Elements

In [6]:
appended = np.append(array, [13, 14]) # Append elements
inserted = np.insert(appended, 2, [0, 0])  # Insert at index 2
deleted = np.delete(inserted, [0, 1])  # Remove first two elements

print("\nOriginal Array:\n", array)
print("\nAppended:\n", appended)
print("\nInserted:\n", inserted)
print("\nDeleted:\n", deleted)


Original Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Appended:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Inserted:
 [ 1  2  0  0  3  4  5  6  7  8  9 10 11 12 13 14]

Deleted:
 [ 0  0  3  4  5  6  7  8  9 10 11 12 13 14]


### 2.3 Stacking Arrays

In [7]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
v_stack = np.vstack((A, B)) # Vertical stack
h_stack = np.hstack((A, B)) # Horizontal stack


print("\nMatrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nVertical Stack:\n", v_stack)
print("\nHorizontal Stack:\n", h_stack)


Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[5 6]
 [7 8]]

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]


### 2.4 Indexing/Slicing

In [8]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("\nMatrix:\n", matrix)

# Indexing and Slicing
print("\nFirst row:", matrix[0])
print("\nLast column:", matrix[:, -1])
print("\nSubmatrix:\n", matrix[1:, :2])

# Boolean Indexing
print("\nMatrix > 5:\n", matrix > 5)
print("\nMatrix[Matrix > 5]:", matrix[matrix > 5])

# Fancy Indexing
rows = [0, 2]
cols = [1, 2]
print("\nSelected elements:", matrix[rows, cols])

# Indexing diagonal elements
rows = list(range(matrix.shape[0]))
cols = list(range(matrix.shape[0]))
print("\nSelected elements:", matrix[rows, cols])


Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

First row: [1 2 3]

Last column: [3 6 9]

Submatrix:
 [[4 5]
 [7 8]]

Matrix > 5:
 [[False False False]
 [False False  True]
 [ True  True  True]]

Matrix[Matrix > 5]: [6 7 8 9]

Selected elements: [2 9]

Selected elements: [1 5 9]


### 2.5 Data Types

In [9]:
float_array = np.array([1.5, 2.2, 3.1], dtype=np.float32) # Array of floats
int_array = float_array.astype(np.int16) # Convert to int16

print("Float Array:", float_array)
print("Int Array:", int_array)

Float Array: [1.5 2.2 3.1]
Int Array: [1 2 3]


## 3 Advanced Level

### 3.1 Broadcasting

In [10]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
result = matrix + np.array([10, 20, 30]) # Add to each row

print("\nMatrix:\n", matrix)
print("\nBroadcasting result:\n", result)


Matrix:
 [[1 2 3]
 [4 5 6]]

Broadcasting result:
 [[11 22 33]
 [14 25 36]]


### 3.2 Vectorization

In [11]:
def slow_func(a, b):
    return a + b * 2

vectorized_func = np.vectorize(slow_func)
result = vectorized_func(np.array([1,2,3]), np.array([4,5,6]))

print(result)

[ 9 12 15]


### 3.3 Linear Algebra

In [12]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
dot_product = np.dot(A, B) # Matrix multiplication
matrix_mult = A @ B  # Alternative syntax
eigenvalues = np.linalg.eig(A)[0] # Eigenvalues of a

print("\nMatrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nDot Product:\n", dot_product)
print("\nMatrix Multiplication:\n", matrix_mult)
print("\nEigenvalues of A:\n", eigenvalues)


Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[5 6]
 [7 8]]

Dot Product:
 [[19 22]
 [43 50]]

Matrix Multiplication:
 [[19 22]
 [43 50]]

Eigenvalues of A:
 [-0.37228132  5.37228132]


### 3.4 Structured Arrays

In [13]:
dtype = [('name', 'S10'), ('age', 'i4'), ('height', 'f4')]
people = np.array([('Alice', 25, 1.65), ('Bob', 30, 1.8)], dtype=dtype)

print("\nStructured array:", people)

print("\nNames:", people['name'])
print("Ages:", people['age'])
print("Heights:", people['height'])


Structured array: [(b'Alice', 25, 1.65) (b'Bob', 30, 1.8 )]

Names: [b'Alice' b'Bob']
Ages: [25 30]
Heights: [1.65 1.8 ]


### 3.5 Advanced Operations

In [14]:
# Conditional operations
arr = np.array([1, 3, 2, 4, 5, 2])
print("Where function:", np.where(arr > 3, arr, -1))

# Unique elements
print("\nUnique values:", np.unique(arr))

# Save/Load
np.save('array.npy', arr)
loaded = np.load('array.npy')
print("\nLoaded array:", loaded)


A = np.array([[1.0, 2.0], [3.0, 4.0]])
print(f"\nA:\n{A}")

# Transpose of a matrix
print(f"\nA.T = \n{A.T}")

# Inverse of a matrix
print(f"\nnp.linalg.inv(A) = \n{np.linalg.inv(A)}")
print(f"\nnp.linalg.inv(A) @ A = \n{np.linalg.inv(A) @ A}")

# Determinant of a matrix
print(f"\nnp.linalg.det(A) = {np.linalg.det(A)}")

Where function: [-1 -1 -1  4  5 -1]

Unique values: [1 2 3 4 5]

Loaded array: [1 3 2 4 5 2]

A:
[[1. 2.]
 [3. 4.]]

A.T = 
[[1. 3.]
 [2. 4.]]

np.linalg.inv(A) = 
[[-2.   1. ]
 [ 1.5 -0.5]]

np.linalg.inv(A) @ A = 
[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]

np.linalg.det(A) = -2.0000000000000004
